#!/usr/bin/env python3
import sys
import time
import colors as c

if len(sys.argv) >= 2:
    start = int(sys.argv[1])
else:
    start = 10

print(c.clear)
print(c.white + 'Counting down from ' + str(start) + c.reset)

for count in range(start,0,-1):
    print(c.pink + str(count) + c.turquoise + ' seconds')
    time.sleep(1)
print('\a')
