#!/usr/bin/env python3
"""The main game engine"""
import colors as c
import json
from player import Player
import monster as m
import random

class Game():
    def __init__(self):
        print(c.clear + 'Welcome')
        self.player = Player()
        

        

    def run(self):
        while True:
            action = input('What do you want to do? ')
            print(c.clear)
            if action == 'stats':
                self.player.show_stats()
            elif action == 'save':
                self.save()
            elif action == 'exit':
                print("Adios!")
                exit()
            elif action in ['pick','choose','decide','repick','re-pick']:
               self.pick_monster()
            elif action in ['bringit','battle','destroy','diediedie']:
                self.handle_battle()
            elif action in ['use']   
                self.handle_use()
    def pick_monster(self):
        count = 1
        for monster in m.monsters:
            pickstr = c.white + "{}. " + c.random_color() +"{}" + c.reset
            print(pickstr.format(count,monster.title))
            count += 1
        number  = int(input().strip().lower())
        monsters_class = m.monsters[number-1]
        monster = monster_class()
        monster.game = self()
        print("You picked {}:".format(monsters_name)) 
        monster.show_stats()    
    
    def handle_battle(self):
        while self.player.hp > 0 and self.monster.hp > 0:
          self.player.pick_move()
          if self.player.speed >= self.monster.speed:
              self.player.move()
              self.monster.move()
          else:
              self.monster.move()
              self.player.move()
        if self.player.hp > 0: #Congratulations on winning, my son
            self.player.xp += self.monster.xp
        else:
            self.player.xp -= self.monster.xp


    def save(self):
        print("would have saved")

    def show_options(self):
        pass

    def load_player(self):
        pass


    def _choose_monster(self):
        pass


if __name__ == '__main__':
    agame = Game()
    agame.run()
