#!/usr/bin/env python3 
import random

answers = [
    '\033[1;31mYes\033[0m',
    '\033[0;35mNo\033[0m',
    'Maybe',
    ]

while True:
   question = input("What is your question? > ").strip().lower()
   answer = random.choice(answers)
   if 'cool' in question:
    print("ICE COLD ALRIGHT ALRIGHT ALRIGHT ALRIGHT ALRIGHT ALRIGHT")
    break
   else:
    print(answer) 




    

