#!/usr/bin/env python3

import random as r 
import colors as c
die = [None]
die.append('''
 -------
|       |
|   .   |
|       |
 -------
''')
die.append('''
 -------
| .     |
|       |
|     . | 
 -------
''')
die.append('''
 -------
| .     |
|   .   |
|     . |
 -------
''')
die.append('''
 -------
| .   . |
|       |
| .   . |
 -------
''')
die.append('''
 -------
| .   . |
|   .   |
| .   . |
 -------
''')
die.append('''
 -------
| .   . |
| .   . |
| .   . |
 -------
''')
how_many = 1
print(c.clear)
while True:
    print(c.clear)
    roll = r.randint(1,6)
    print(c.random_color() + die[roll] + c.reset)
    input("> ")
